REPLACE INTO ?:page_descriptions (page_id, page, description, lang_code) VALUES('7', 'Manufacturers', '', 'en');

REPLACE INTO ?:page_descriptions (page_id, page, description, lang_code) VALUES('40', 'Ergom', '<p>Ergom is the core brand of the catalog. It covers the main product line for everyday professional use: reliable tools and equipment that are tested for continuous load.</p><!--CUT--><p><b>Why choose Ergom:</b><ul><li>Wide range of positions for repair, assembly and maintenance.</li><li>Durable housing and wear-resistant parts.</li><li>Documents and specifications available for every item.</li></ul><p>Ergom is the recommended choice when you need a balance of price and reliability.</p>', 'en');

REPLACE INTO ?:page_descriptions (page_id, page, description, lang_code) VALUES('41', 'Ergom PRO', '<p>Ergom PRO is the professional line of the brand. It is designed for daily work under high load, for service crews and for the users who cannot afford downtime.</p><!--CUT--><p><b>What makes Ergom PRO different:</b><ul><li>Reinforced body and increased service life.</li><li>Higher accuracy and stable performance at extreme conditions.</li><li>Extended warranty and availability of spare parts.</li></ul>', 'en');

REPLACE INTO ?:page_descriptions (page_id, page, description, lang_code) VALUES('42', 'Ergom Safety', '<p>Ergom Safety is dedicated to protective equipment and workplace safety. Every item is certified and selected to reduce the risk of injury during work.</p><!--CUT--><p><b>Product range:</b><ul><li>Protective gloves, eyewear and helmets.</li><li>High-visibility clothing.</li><li>Insulating and protective equipment.</li></ul><p>All products of this line are marked with the <b>Safety</b> badge in the catalog, so they can be filtered in one click.</p>', 'en');

REPLACE INTO ?:page_descriptions (page_id, page, description, lang_code) VALUES('43', 'Ergom OEM', '<p>Ergom OEM is the private label line of the brand. It is produced under the specifications of the customer and is used for retail chains and corporate programs.</p><!--CUT--><p><b>OEM capabilities:</b><ul><li>Own branding and packaging.</li><li>Adaptation of the product range to the customer assortment.</li><li>Batch supply with individual product cards.</li></ul>', 'en');
